EMedSovet.Web/Models/Disease.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using EMedSovet.Web.Properties;

namespace EMedSovet.Web.Models
{
    public class Disease
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int DiseaseId { get; set; }
        [Display(Name = "Name", ResourceType = typeof(Resources))]
        [MaxLength(250)]
        public string Name { get; set; }
        [Display(Name = "Description", ResourceType = typeof(Resources))]
        public string Description { get; set; }
        [Display(Name = "Article", ResourceType = typeof(Resources))]
        [MaxLength(500)]
        public string Article { get; set; }
    }
}

EMedSovet.Web/Controllers/DiseaseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EMedSovet.Web.Models;

namespace EMedSovet.Web.Controllers
{
    public class DiseaseController : Controller
    {
        private EMedSovetEntities db = new EMedSovetEntities();

        //
        // GET: /Disease/

        public ActionResult Index()
        {
            return View(db.Diseases.ToList());
        }

        //
        // GET: /Disease/Details/5

        public ActionResult Details(int id = 0)
        {
            Disease disease = db.Diseases.Find(id);
            if (disease == null)
            {
                return HttpNotFound();
            }
            return View(disease);
        }

        //
        // GET: /Disease/Create

        public ActionResult Create()
        {
            ViewBag.Articles = new SelectList(GetArticleList());
            return View();
        }

        //
        // POST: /Disease/Create

        [HttpPost]
        public ActionResult Create(Disease disease)
        {
            ViewBag.Articles = new SelectList(GetArticleList());
            if (ModelState.IsValid)
            {
                HttpPostedFileBase hpf = null;
                foreach (string input in Request.Files)
                {
                    hpf = Request.Files[input];
                    if (hpf == null) continue;
                    if (hpf.ContentLength == 0)
                        continue;
                    var fileInfo = new FileInfo(hpf.FileName);
                    if (fileInfo.Extension != ".html") hpf = null;
                }
                if (hpf == null)
                {
                    ModelState.AddModelError("Common", "File can be only html type");
                    return View(disease);
                }
                if (hpf.ContentLength != 0)
                {
                    var articleDirectoryPath = string.Format("{0}\\{1}\\",
                                                        ControllerContext.HttpContext.Server.MapPath(
                                                            ControllerContext.HttpContext.Request.ApplicationPath), "Articles");
                    if (!Directory.Exists(articleDirectoryPath)) Directory.CreateDirectory(articleDirectoryPath);
                    var articleList = GetArticleList();
                    if (articleList.Contains(hpf.FileName))
                    {
                        ModelState.AddModelError("Common", "File with this name already exists");
                        return View(disease);
                    }

                    var savedFileName = Path.Combine(articleDirectoryPath, hpf.FileName);

                    hpf.SaveAs(savedFileName);
                    disease.Article = hpf.FileName;
                }
                db.Diseases.Add(disease);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(disease);
        }

        //
        // GET: /Disease/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Disease disease = db.Diseases.Find(id);
            ViewBag.Articles = new SelectList(GetArticleList());
            if (disease == null)
            {

                return HttpNotFound();
            }
            return View(disease);
        }

        private IEnumerable<string> GetArticleList()
        {
            var articleDirectoryPath = string.Format("{0}\\{1}\\",
                                             ControllerContext.HttpContext.Server.MapPath(
                                                 ControllerContext.HttpContext.Request.ApplicationPath), "Articles");
            var files = new List<string>();
            if (!Directory.Exists(articleDirectoryPath)) return files;
            foreach (var file in Directory.GetFiles(articleDirectoryPath))
            {
                var fileInfo = new FileInfo(file);
                if (fileInfo.Extension == ".html")
                    files.Add(fileInfo.Name);
            }
            return files;
        }

        //
        // POST: /Disease/Edit/5

        [HttpPost]
        public ActionResult Edit(Disease disease)
        {
            if (ModelState.IsValid)
            {

                db.Entry(disease).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(disease);
        }

        //
        // GET: /Disease/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Disease disease = db.Diseases.Find(id);
            if (disease == null)
            {
                return HttpNotFound();
            }
            return View(disease);
        }

        //
        // POST: /Disease/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Disease disease = db.Diseases.Find(id);
            db.Diseases.Remove(disease);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

EMedSovet.Web/Views/Disease/Create.cshtml
@model EMedSovet.Web.Models.Disease

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Main.cshtml";
}

<div class="row">

    <div class="span12 topMarginSmall bottomMarginSmall">
        <div class="leftMargin inner-body">

            @using (Html.BeginForm("Create", "Disease", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
                @Html.ValidationSummary(true)
                 @Html.ValidationMessage("Common")

                <fieldset>
                    <legend>Создать</legend>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.Name)
                    </div>
                    <div class="editor-field">
                        @Html.EditorFor(model => model.Name)
                        @Html.ValidationMessageFor(model => model.Name)
                    </div>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.Description)
                    </div>
                    <div class="editor-field">
                        @Html.EditorFor(model => model.Description)
                        @Html.ValidationMessageFor(model => model.Description)
                    </div>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.Article)
                    </div>
                    <div class="editor-field">
                        @Html.DropDownList("Article", (SelectList)ViewBag.Articles)
                        @Html.ValidationMessageFor(model => model.Article)
                    </div>
                    
                     <div class="editor-label">
                        Загрузить статью
                    </div>
                    <div class="editor-field">
                        <input type="file" name="ArticleHtml"/>
                    </div>

                    <p>
                        <input type="submit" value="Создать" />
                    </p>
                </fieldset>
            }

            <div>
                @Html.ActionLink("Список заболеваний", "Index")
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EMedSovet.Web/Views/Disease/Delete.cshtml
@model EMedSovet.Web.Models.Disease

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Main.cshtml";
}

<div class="row">

    <div class="span12 topMarginSmall bottomMarginSmall">
        <div class="leftMargin inner-body">

            <h3>Вы уверены что хотите удалить?</h3>
            <fieldset>
                <legend>Удалить</legend>

                <div class="display-label">
                    @Html.DisplayNameFor(model => model.Name)
                </div>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Name)
                </div>

                <div class="display-label">
                    @Html.DisplayNameFor(model => model.Description)
                </div>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Description)
                </div>

                <div class="display-label">
                    @Html.DisplayNameFor(model => model.Article)
                </div>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Article)
                </div>
            </fieldset>
            @using (Html.BeginForm())
            {
                <p>
                    <input type="submit" value="Удалить" />
                    |
        @Html.ActionLink("Список заболеваний", "Index")
                </p>
            }
        </div>
    </div>
</div>

EMedSovet.Web/Views/Disease/Details.cshtml
@model EMedSovet.Web.Models.Disease

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Main.cshtml";
}

<div class="row">

    <div class="span12 topMarginSmall bottomMarginSmall">
        <div class="leftMargin inner-body">

            <fieldset>
                <legend>Детали</legend>

                <div class="display-label">
                    @Html.DisplayNameFor(model => model.Name)
                </div>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Name)
                </div>

                <div class="display-label">
                    @Html.DisplayNameFor(model => model.Description)
                </div>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Description)
                </div>

                <div class="display-label">
                    @Html.DisplayNameFor(model => model.Article)
                </div>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Article)
                </div>
            </fieldset>
            <p>
                @Html.ActionLink("Редактировать", "Edit", new { id = Model.DiseaseId }) |
    @Html.ActionLink("Список заболеваний", "Index")
            </p>
        </div>
    </div>
</div>

EMedSovet.Web/Views/Disease/Edit.cshtml
@model EMedSovet.Web.Models.Disease

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Main.cshtml";
}

<div class="row">

    <div class="span12 topMarginSmall bottomMarginSmall">
        <div class="leftMargin inner-body">

            @using (Html.BeginForm())
            {
                @Html.ValidationSummary(true)

                <fieldset>
                    <legend>Редактировать</legend>

                    @Html.HiddenFor(model => model.DiseaseId)

                    <div class="editor-label">
                        @Html.LabelFor(model => model.Name)
                    </div>
                    <div class="editor-field">
                        @Html.EditorFor(model => model.Name)
                        @Html.ValidationMessageFor(model => model.Name)
                    </div>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.Description)
                    </div>
                    <div class="editor-field">
                        @Html.EditorFor(model => model.Description)
                        @Html.ValidationMessageFor(model => model.Description)
                    </div>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.Article)
                    </div>
                    <div class="editor-field">
                        @Html.DropDownList("Article", (SelectList)ViewBag.Articles)
                        @Html.ValidationMessageFor(model => model.Article)
                    </div>

                    <p>
                        <input type="submit" value="Редактировать" />
                    </p>
                </fieldset>
            }

            <div>
                @Html.ActionLink("Список заболеваний", "Index")
            </div>

        </div>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EMedSovet.Web/Views/Disease/Index.cshtml
@model IEnumerable<EMedSovet.Web.Models.Disease>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Main.cshtml";
}

<div class="row">

    <div class="span12 topMarginSmall bottomMarginSmall">
        <div class="leftMargin inner-body">

            <p>
                @Html.ActionLink("Создать новое", "Create")
            </p>
            <table>
                <tr>
                    <th class="text-left-aligned bold" style="width: 100px;">
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th class="text-left-aligned bold" style="width: 100px;">
                        @Html.DisplayNameFor(model => model.Description)
                    </th>
                    <th class="text-left-aligned bold word-wrap-break" style="width: 400px;">
                        @Html.DisplayNameFor(model => model.Article)
                    </th>
                    <th class="text-left-aligned bold" style="width: 400px;"></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td class="text-left-aligned" style="width: 100px;">
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td class="text-left-aligned" style="width: 100px;">
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td class="text-left-aligned word-wrap-break" style="width: 400px;">
                            @Html.DisplayFor(modelItem => item.Article)
                        </td>
                        <td class="text-left-aligned" style="width: 400px;">
                            @Html.ActionLink("Редактировать", "Edit", new { id = item.DiseaseId }) |
                            @Html.ActionLink("Детали", "Details", new { id = item.DiseaseId }) |
                            @Html.ActionLink("Удалить", "Delete", new { id = item.DiseaseId }) | 
                            <a href="~/Articles/@item.Article" class="fancybox">Статья</a>
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>
</div>


@section scripts
{
    @Scripts.Render("~/bundles/fancybox/js")
    <script>
        $(function () {
            $('.fancybox').fancybox({
                //'padding': 10,
                'width': 800,
                'height': 600,
                'autoScale': false,
                'transitionIn': 'none',
                'transitionOut': 'none',
                'type': 'iframe',
                'scrolling': 'no',
                'padding': 0
            });
        });
    </script>
}