EMedSovet.Web/Models/Symptom.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using EMedSovet.Web.Properties;

namespace EMedSovet.Web.Models
{
    public class Symptom
    {
        public Symptom()
        {
            Patient = new HashSet<Patient>();
        }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int SymptomId { get; set; }
        [Display(Name = "Name", ResourceType = typeof(Resources))]
        [MaxLength(500)]
        public string Name { get; set; }
        [Display(Name = "Description", ResourceType = typeof(Resources))]
        public string Description { get; set; }

        public ICollection<Patient> Patient { get; set; }
    }
}

EMedSovet.Web/Controllers/SymptomController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EMedSovet.Web.Models;

namespace EMedSovet.Web.Controllers
{
    public class SymptomController : Controller
    {
        private readonly EMedSovetEntities _db = new EMedSovetEntities();

        //
        // GET: /Symptom/

        
        public ActionResult ChooseSymptoms()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GetSymptoms(string bodyPart, string sex)
        {
            return Json(_db.Symptoms.ToList());
        }

        public ActionResult Index()
        {
            return View(_db.Symptoms.ToList());
        }

        //
        // GET: /Symptom/Details/5

        public ActionResult Details(int id = 0)
        {
            Symptom symptom = _db.Symptoms.Find(id);
            if (symptom == null)
            {
                return HttpNotFound();
            }
            return View(symptom);
        }

        //
        // GET: /Symptom/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Symptom/Create

        [HttpPost]
        public ActionResult Create(Symptom symptom)
        {
            if (ModelState.IsValid)
            {
                _db.Symptoms.Add(symptom);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(symptom);
        }

        //
        // GET: /Symptom/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Symptom symptom = _db.Symptoms.Find(id);
            if (symptom == null)
            {
                return HttpNotFound();
            }
            return View(symptom);
        }

        //
        // POST: /Symptom/Edit/5

        [HttpPost]
        public ActionResult Edit(Symptom symptom)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(symptom).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(symptom);
        }

        //
        // GET: /Symptom/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Symptom symptom = _db.Symptoms.Find(id);
            if (symptom == null)
            {
                return HttpNotFound();
            }
            return View(symptom);
        }

        //
        // POST: /Symptom/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Symptom symptom = _db.Symptoms.Find(id);
            _db.Symptoms.Remove(symptom);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
            base.Dispose(disposing);
        }
    }
}

EMedSovet.Web/Views/Symptom/ChooseSymptoms.cshtml
@{
    ViewBag.Title = "ChooseSymptoms";
    Layout = "~/Views/Shared/_Main.cshtml";
}

<div class="row">

    <div class="span12 topMarginSmall bottomMarginSmall">
        <div class="leftMargin inner-body">
            <div id="symptoms_people">
                <div id="symptoms_checkbox">
                    
                </div>

                <div class="symptoms_male symptoms_body">
                    <a class="arr180" href="#">180°</a>
                    <a href="#" id="foot_l" class="foot inactive"></a>
                    <a href="#" id="foot_r" class="foot inactive"></a>
                    <a href="#" id="leg_l" class="leg inactive"></a>
                    <a href="#" id="leg_r" class="leg inactive"></a>
                    <a href="#" id="palm_l" class="palm inactive"></a>
                    <a href="#" id="palm_r" class="palm inactive"></a>
                    <a href="#" id="hand_l" class="hand inactive"></a>
                    <a href="#" id="hand_r" class="hand inactive"></a>
                    <a href="#" id="stomack_1" class="stomack_1 inactive"></a>
                    <a href="#" id="stomack_2" class="stomack_2 inactive"></a>
                    <a href="#" id="back" class="back inactive"></a>
                    <a href="#" id="chest" class="chest inactive"></a>
                    <a href="#" id="neck" class="neck inactive"></a>
                    <a href="#" id="head" class="head inactive"></a>
                    <a href="#" id="head_back" class="head_back inactive"></a>
                    <a href="#" id="mouth" class="mouth inactive"></a>
                    <a href="#" id="eyes" class="eyes inactive"></a>
                    <a href="#" id="ear_l" class="ear inactive"></a>
                    <a href="#" id="ear_r" class="ear inactive"></a>
                    <a href="#" id="nose" class="nose inactive"></a>
                    <a href="#" id="hair" class="hair inactive"></a>
                    <a href="#" id="common" class="common inactive">Общее самочувствие</a>
                </div>

                <div class="symptoms_female symptoms_body">
                    <a class="arr180" href="#">180°</a>
                    <a href="#" id="foot_l" class="foot inactive"></a>
                    <a href="#" id="foot_r" class="foot inactive"></a>
                    <a href="#" id="leg_l" class="leg inactive"></a>
                    <a href="#" id="leg_r" class="leg inactive"></a>
                    <a href="#" id="palm_l" class="palm inactive"></a>
                    <a href="#" id="palm_r" class="palm inactive"></a>
                    <a href="#" id="hand_l" class="hand inactive"></a>
                    <a href="#" id="hand_r" class="hand inactive"></a>
                    <a href="#" id="stomack_1" class="stomack_1 inactive"></a>
                    <a href="#" id="stomack_2" class="stomack_2 inactive"></a>
                    <a href="#" id="back" class="back inactive"></a>
                    <a href="#" id="chest" class="chest inactive"></a>
                    <a href="#" id="neck" class="neck inactive"></a>
                    <a href="#" id="head" class="head inactive"></a>
                    <a href="#" id="head_back" class="head_back inactive"></a>
                    <a href="#" id="mouth" class="mouth inactive"></a>
                    <a href="#" id="eyes" class="eyes inactive"></a>
                    <a href="#" id="ear_l" class="ear inactive"></a>
                    <a href="#" id="ear_r" class="ear inactive"></a>
                    <a href="#" id="nose" class="nose inactive"></a>
                    <a href="#" id="hair" class="hair inactive"></a>
                    <a href="#" id="common" class="common inactive">Общее самочувствие</a>
                </div>
            </div>
            <div id="symptoms_summary">
                <h5>Выбранные симптомы</h5>
                <div id="symptoms_checked">
                    
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts
{
    <script type="text/javascript">
        var symptomsOptions = {
            jsonGetSymptoms : '@Html.Raw(@Url.Action("GetSymptoms", "Symptom"))'

        }
    </script>
    @Scripts.Render("~/bundles/symptoms")

}

EMedSovet.Web/Views/Symptom/Create.cshtml
@model EMedSovet.Web.Models.Symptom

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Main.cshtml";
}

<div class="row">

    <div class="span12 topMarginSmall bottomMarginSmall">
        <div class="leftMargin inner-body">

            @using (Html.BeginForm())
            {
                @Html.ValidationSummary(true)

                <fieldset>
                    <legend>Symptom</legend>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.Name)
                    </div>
                    <div class="editor-field">
                        @Html.EditorFor(model => model.Name)
                        @Html.ValidationMessageFor(model => model.Name)
                    </div>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.Description)
                    </div>
                    <div class="editor-field">
                        @Html.EditorFor(model => model.Description)
                        @Html.ValidationMessageFor(model => model.Description)
                    </div>

                    <p>
                        <input type="submit" value="Создать" />
                    </p>
                </fieldset>
            }

            <div>
                @Html.ActionLink("Список симптомов", "Index")
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EMedSovet.Web/Views/Symptom/Delete.cshtml
@model EMedSovet.Web.Models.Symptom

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Main.cshtml";
}

<div class="row">

    <div class="span12 topMarginSmall bottomMarginSmall">
        <div class="leftMargin inner-body">

            <h3>Вы уверены что хотите удалить?</h3>
            <fieldset>
                <legend>Symptom</legend>

                <div class="display-label">
                    @Html.DisplayNameFor(model => model.Name)
                </div>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Name)
                </div>

                <div class="display-label">
                    @Html.DisplayNameFor(model => model.Description)
                </div>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Description)
                </div>
            </fieldset>
            @using (Html.BeginForm())
            {
                <p>
                    <input type="submit" value="Удалить" />
                    |
        @Html.ActionLink("Список симптомов", "Index")
                </p>
            }

        </div>
    </div>
</div>

EMedSovet.Web/Views/Symptom/Details.cshtml
@model EMedSovet.Web.Models.Symptom

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Main.cshtml";
}

<div class="row">

    <div class="span12 topMarginSmall bottomMarginSmall">
        <div class="leftMargin inner-body">

            <fieldset>
                <legend>Symptom</legend>

                <div class="display-label">
                    @Html.DisplayNameFor(model => model.Name)
                </div>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Name)
                </div>

                <div class="display-label">
                    @Html.DisplayNameFor(model => model.Description)
                </div>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Description)
                </div>
            </fieldset>
            <p>
                @Html.ActionLink("Редактировать", "Edit", new { id = Model.SymptomId }) |
    @Html.ActionLink("Список симптомов", "Index")
            </p>
        </div>
    </div>
</div>

EMedSovet.Web/Views/Symptom/Edit.cshtml
@model EMedSovet.Web.Models.Symptom

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Main.cshtml";
}

<div class="row">

    <div class="span12 topMarginSmall bottomMarginSmall">
        <div class="leftMargin inner-body">

            @using (Html.BeginForm())
            {
                @Html.ValidationSummary(true)

                <fieldset>
                    <legend>Symptom</legend>

                    @Html.HiddenFor(model => model.SymptomId)

                    <div class="editor-label">
                        @Html.LabelFor(model => model.Name)
                    </div>
                    <div class="editor-field">
                        @Html.EditorFor(model => model.Name)
                        @Html.ValidationMessageFor(model => model.Name)
                    </div>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.Description)
                    </div>
                    <div class="editor-field">
                        @Html.EditorFor(model => model.Description)
                        @Html.ValidationMessageFor(model => model.Description)
                    </div>

                    <p>
                        <input type="submit" value="Сохранить" />
                    </p>
                </fieldset>
            }

            <div>
                @Html.ActionLink("Список симптомов", "Index")
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EMedSovet.Web/Views/Symptom/Index.cshtml
@model IEnumerable<EMedSovet.Web.Models.Symptom>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Main.cshtml";
}

<div class="row">

    <div class="span12 topMarginSmall bottomMarginSmall">
        <div class="leftMargin inner-body">

            <p>
                @Html.ActionLink("Создать новый", "Create")
            </p>
            <table>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Description)
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            @Html.ActionLink("Редактировать", "Edit", new { id = item.SymptomId }) |
            @Html.ActionLink("Детали", "Details", new { id = item.SymptomId }) |
            @Html.ActionLink("Удалить", "Delete", new { id = item.SymptomId })
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>
</div>